using System;
using System.Linq;
using Xunit;

namespace Rosalind_CSharp
{
    public class Counting_DNA_Nucleotides
    {
        [Fact]
        public void SampleData()
        {
            var actualResult = Count("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC");
            Assert.Equal("20 12 17 21", actualResult);
        }

        [Fact]
        public void RealData()
        {
            var actualResult = Count("GCGGGACCGAAGTCCCACGTGTTAATTTGTGCGGCCAGGAAACAAGCTGACTTTACCTAACTTTGGTGCCTCACATTTCGTGTTCGAAACCAAGTCGGACCAGGCTTCGTCCGCATGTCTACAGTAGAGTCTCTAGCACTTGCGATACCGTGGCGAGTTCAGCGCGTTACTCCTCTTACCAAACAGCAGACTGGTGGAGCTTAAGTGGCAACTAGCAGAGAACTCGATAGTGTCACCAACCGTCGTCCAATACCACGGTCGGGGGCCAACACTTCGTGAGGGTATATGCGTATTATCTGCGGTATTCCATATCCGCACCAACGGGACCGAATGGTCCCTCCGGTCAACGGCCCGACACTAAATTAACAACGCCACATCCAAGCCAGTCGGCTTGTTTGAGCACCTATAATATACGTTCCTCAGTTCCGAAGTTACCAGCAGCGAGAGATGCTCTTTCAGAGATCAGGCATGATCTGGCTGACTGTGGGTTGACGGGACGACTATCATTTGAAGCAATTTTTTTCCCATAGAGACTGGCGTCTATCCGGCATATGAAACACTGTAGAGGAGAAGGCGCGCGAGTAGCAAAAATGATGTCAGCACTAATATGCATTTCTTCAAGAAAGGTGTAGTTACGAAATGGTACGACTTTTGGACGTTCGGCGTTCGCACATGCAGCCGAATCTCAGATGGGTTGAGCAACGTATACCTAATTGTCGAAATCCAGCACTGCCTCGCCTGTAGTGCGAGAACGTGGATCTGCAGTTAGAGTTGAGCATGATTTGGCGGTAACATATCCATCGCCGGGCGTTCTAGGCTCCGATAGGCGTTTGTTTCCTATCCAAGTGAAGCTACCGTCTGACATTTCCCTATATTAAGTAGGCGTGGAGCACCATGGACCAAGGCACCTTGCAACCGCATGTTCCGGGGGATCGGCGCTTCCGGGGACTTACCAG");
            Assert.Equal("236 241 246 233", actualResult);
        }

        private string Count(string dnaString)
        {
            var groups = dnaString.GroupBy(l => l)
                                  .OrderBy(g => g.Key)
                                  .Select(g => g.Count());
            return string.Join(' ', groups);
        }
    }
}
